apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-aws-monitor.fullname" . }}
  labels:
    {{- include "flask-aws-monitor.labels" . | nindent 4 }}
spec:
  type: {{ ternary "ClusterIP" "LoadBalancer" .Values.ingress.enabled }}
  selector:
    {{- include "flask-aws-monitor.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}